import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full min-h-screen bg-neutral-100 dark:bg-neutral-900">
        <Image src="/factor.svg" width="100" height="100" alt="Factor logo" className="text-white" />
      </main>
    </div>
  )
}
